#ifndef _USART_H_
#define _USART_H_

/* Config properties */
#define USART_PIN1 2
#define USART_PIN2 3
#define USART_PIN_GROUP_ID A
#define USART_ID 2

/*
 * This ugly set of macros allows us to create defines like this one:
 * String ## ID => String3
 */
#define __USART_PERIPH_BUS_ID(ID) RCC_APB1Periph_USART ## ID
#define _USART_PERIPH_BUS_ID(ID) __USART_PERIPH_BUS_ID(ID)
#define USART_PERIPH_BUS_ID _USART_PERIPH_BUS_ID(USART_ID)

#define __USART_PERIPH_PIN_GROUP_BUS_ID(ID) RCC_AHB1Periph_GPIO ## ID
#define _USART_PERIPH_PIN_GROUP_BUS_ID(ID) __USART_PERIPH_PIN_GROUP_BUS_ID(ID)
#define USART_PERIPH_PIN_GROUP_BUS_ID _USART_PERIPH_PIN_GROUP_BUS_ID(USART_PIN_GROUP_ID)

#define __USART_GPIO_AF(ID) GPIO_AF_USART ## ID
#define _USART_GPIO_AF(ID) __USART_GPIO_AF(ID)
#define USART_GPIO_AF _USART_GPIO_AF(USART_ID)

#define __USART_PIN_GROUP(ID) GPIO ## ID
#define _USART_PIN_GROUP(ID) __USART_PIN_GROUP(ID)
#define USART_PIN_GROUP _USART_PIN_GROUP(USART_PIN_GROUP_ID)

#define __USART_NAME(ID) USART ## ID
#define _USART_NAME(ID) __USART_NAME(ID)
#define USART_NAME _USART_NAME(USART_ID)

#define __USART_GPIO_PIN(ID) GPIO_Pin_ ## ID
#define _USART_GPIO_PIN(ID) __USART_GPIO_PIN(ID)
#define USART_GPIO_PIN1 _USART_GPIO_PIN(USART_PIN1)
#define USART_GPIO_PIN2 _USART_GPIO_PIN(USART_PIN2)

#define __USART_GPIO_PIN_SOURCE(ID) GPIO_PinSource ## ID
#define _USART_GPIO_PIN_SOURCE(ID) __USART_GPIO_PIN_SOURCE(ID)
#define USART_GPIO_PIN_SOURCE1 _USART_GPIO_PIN_SOURCE(USART_PIN1)
#define USART_GPIO_PIN_SOURCE2 _USART_GPIO_PIN_SOURCE(USART_PIN2)

void USART_init();
unsigned char USART_ReadByteSync(USART_TypeDef *USARTx);

#endif
